In [1]:
import numpy as np

# Construct the Reward matrix

In [2]:
R= np.matrix([
    
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,0,-1],
    [-1,0,0,-1,-1,100],
    [-1,0,-1,-1,0,100]
])
print(R)

[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0  -1  -1   0 100]]


# Construct the zero matrix of the size of R matrix to form Q matric

In [3]:
Q= np.matrix(np.zeros([6,6]))
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Define gamma value - Learning Parameter

In [4]:
gamma=0.8

# Q - Learning:
    Q(state,action )= R(state,action) +gamma* Max(Q(next state,all actions))

# Initial state(usually to be choosen as random)

In [5]:
initial_state =1

# Define the Available action function:
this function returns all the available actions in the state given as an arguments

In [6]:
def available_act(state):
    current_state_row=R[state,]
    av_act= np.where(current_state_row>=0)[1]
    return av_act

In [7]:
available_act= available_act(initial_state)
print(available_act)

[3 5]


In [8]:
#Define the sample next action funtion

def sample_next_action(available_actions_range):
    next_action=int(np.random.choice(available_act,1))
    return next_action

In [16]:
action = sample_next_action(available_act)
print(action)

5


# Q Matrix - Update fun

In [11]:
def update(current_state,action,gamma):
    #Max(Q(next state,all actions))
    max_index=np.where(Q[action]==np.max(Q[action,]))[1]
    
    if max_index.shape[0]>1:
        max_index= int (np.random.choice(max_index,size =1))
    
    else:
        max_index=int(max_index)
                       
    max_value=Q[action,max_index]
                       
    Q[current_state,action] = R[current_state,action]+gamma*max_value

In [12]:
update(initial_state,action,gamma)

# train the agent whith this enviorment information

In [13]:
for i in range(1000000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    acton=sample_next_action(available_act)
    update(current_state,action,gamma)

# Testing
goal_state=5

In [14]:
current_state=4
steps=[current_state]
while current_state !=5:
    next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index=int (np.random.choice(next_step_index,size=1))
    else:
        next_step_index=int (next_step_index)
    steps.append(next_step_index)
    current_state= next_step_index
    
print('Optimum path of initial state {} to the Goal state is {}'.format(initial_state,steps))

Optimum path of initial state 1 to the Goal state is [4, 4, 2, 2, 3, 0, 4, 0, 2, 3, 1, 4, 0, 2, 2, 3, 5]
